### ISSUE TITLE
Saving the best model during training in Fewshot!!!

### ISSUE THREAD

**Issue by aminpdik** [juhongm999/hsnet#20]
Hi @juhongm999 

Thank you for the code and the great new approach for few-shot segmentation.

I have several questions that would be great If you answer.

As I see in the code, you are saving the best model by validating on validation data of the current fold (Pascal dataset) in every epoch of training. Am I right? In pascal dataset validation data are used for reporting the MIOU and should not be used during training. You are using 2000 epochs and trying to save the best model!

For reporting the model accuracy, most of the papers in few-shot segmentation are using Kfold experimenting. As I see in your code you report the accuracy just by one try. Is it right?

Best

**Comment by juhongm999** [comment]
As I see in the code, you are saving the best model by validating on validation data of the current fold (Pascal dataset) in every epoch of training. Am I right? In pascal dataset validation data are used for reporting the MIOU and should not be used during training. You are using 2000 epochs and trying to save the best model!

- This issue was answered in #12 

For reporting the model accuracy, most of the papers in few-shot segmentation are using Kfold experimenting. As I see in your code you report the accuracy just by one try. Is it right?

- We did perform K-fold cross-validation on PASCAL-5i and COCO-20i. Please refer to the Table 1 in our paper.
